// Player queries stay in the Page layer; server and Wiki code remains in core.js.
var HISTORY_KEY='minecraft-hub.players.history.v1';
var PLATFORM_KEY='minecraft-hub.players.platform.v1';
var CACHE_MS=5*60*1000;
var cache=new Map();
var history=[];
var platform='java';
var sequence=0;
var viewer=null;
var observer=null;
function el(id){return document.getElementById(id)}
function escapeHtml(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function dataOf(value){return value&&value.success===true&&Object.prototype.hasOwnProperty.call(value,'data')?value.data:value}
function error(code){var e=new Error(code);e.code=code;return e}
function uuid(raw){var value=String(raw||'').replace(/-/g,'').toLowerCase();return /^[0-9a-f]{32}$/.test(value)?value:null}
function floodgateXuid(raw){var value=String(raw||'').toLowerCase();if(!/^00000000-0000-0000-[0-9a-f]{4}-[0-9a-f]{12}$/.test(value))return null;var xuid=BigInt('0x'+value.slice(19).replace('-','')).toString(10);return xuid==='0'?null:xuid}
function formattedUuid(value){return value.slice(0,8)+'-'+value.slice(8,12)+'-'+value.slice(12,16)+'-'+value.slice(16,20)+'-'+value.slice(20)}
function textureUrl(raw){var match=/^https?:\/\/textures\.minecraft\.net\/texture\/([a-f0-9]{20,128})$/i.exec(String(raw||''));return match?'https://textures.minecraft.net/texture/'+match[1]:null}
function bedrockSkinUrl(raw){var id=String(raw||'');return /^[a-f0-9]{64}$/i.test(id)?'https://api.geysermc.org/render/raw/'+id.toLowerCase():null}
function classify(e){if(e&&e.code)return e.code;var message=String(e&&e.message||e||'');if(/(^|\D)404(\D|$)|not found/i.test(message))return'not-found';if(/(^|\D)429(\D|$)|rate limit|too many/i.test(message))return'rate-limited';return'network-error'}
function message(code){return{'not-found':'没有找到该玩家，请检查名称或 ID。','invalid':'输入格式无效，请检查后重试。','invalid-gamertag':'请输入 1–16 个字符的 Xbox Gamertag，或使用十进制 XUID。','uuid-not-xuid':'这是 UUID，不是 Xbox XUID。Bedrock 请使用十进制 XUID 或 Gamertag；如需查询 Java UUID，可切换到 Java。','network-error':'当前数据源暂时无法访问，请稍后重试。','rate-limited':'查询过于频繁，请稍后再试。','unsupported':'当前平台暂不支持无登录资料查询。'}[code]||'查询失败，请稍后再试。'}
function ensurePayload(value){if(!value||typeof value!=='object'||value.error||value.errorMessage)throw error('not-found');return value}
async function javaProvider(input){var id=uuid(input),lookup=null;if(!id){if(!/^[A-Za-z0-9_]{3,16}$/.test(input))throw error('invalid');lookup=ensurePayload(dataOf(await Tapp.api('javaPlayerByName',{name:input})));id=uuid(lookup.id);if(!id)throw error('not-found')}
  var raw=ensurePayload(dataOf(await Tapp.api('javaPlayerProfile',{uuid:id})));var properties=Array.isArray(raw.properties)?raw.properties:[];var prop=properties.find(function(x){return x&&x.name==='textures'&&typeof x.value==='string'});var textures={};if(prop){try{textures=JSON.parse(atob(prop.value)).textures||{}}catch(e){textures={}}}
  var skin=textureUrl(textures.SKIN&&textures.SKIN.url),cape=textureUrl(textures.CAPE&&textures.CAPE.url),model=skin?(textures.SKIN&&textures.SKIN.metadata&&String(textures.SKIN.metadata.model).toLowerCase()==='slim'?'slim':'classic'):null;var name=String(raw.name||lookup&&lookup.name||'').trim();if(!uuid(raw.id)||!name)throw error('not-found');return{platform:'java',username:name,playerId:formattedUuid(id),idType:'UUID',avatar:null,skin:skin,cape:cape,model:model,details:[]}}
async function bedrockProvider(input){var raw,tag=null,xuid=null,converted=floodgateXuid(input);if(/^\d{1,20}$/.test(input)||converted){xuid=converted||input;raw=ensurePayload(dataOf(await Tapp.api('bedrockGamertag',{xuid:xuid})));tag=String(raw.gamertag||'').trim()}else{if(uuid(input))throw error('uuid-not-xuid');if(!/^[\p{L}\p{N}_ .-]{1,16}$/u.test(input))throw error('invalid-gamertag');raw=ensurePayload(dataOf(await Tapp.api('bedrockXuid',{gamertag:encodeURIComponent(input)})));xuid=String(raw.xuid||'').trim();tag=input}
  if(!/^\d{1,20}$/.test(xuid)||!tag)throw error('not-found');var skin=null;try{var skinData=dataOf(await Tapp.api('bedrockSkin',{xuid:xuid}));skin=bedrockSkinUrl(skinData&&skinData.texture_id)}catch(e){}return{platform:'bedrock',username:tag,playerId:xuid,idType:'XUID',avatar:null,skin:skin,cape:null,model:null,details:[{label:'Skin',value:skin?'GeyserMC 最近缓存的转换贴图':'暂无 GeyserMC 缓存贴图'}].concat(converted?[{label:'输入',value:'Floodgate UUID 已转换为 XUID'}]:[])}}
async function neteaseProvider(input){if(!/^\d{1,20}$/.test(input))throw error('invalid');throw error('unsupported')}
var providers={java:javaProvider,bedrock:bedrockProvider,netease:neteaseProvider};
function renderHistory(){var box=el('player-history-list');if(!box)return;box.innerHTML=history.length?history.map(function(item){return'<button type="button" data-platform="'+escapeHtml(item.platform)+'" data-query="'+escapeHtml(item.query)+'">'+escapeHtml(item.query)+' <small>'+escapeHtml(item.platform==='java'?'Java':'Bedrock')+'</small></button>'}).join(''):'<p class="muted">暂无玩家查询记录</p>';box.querySelectorAll('button').forEach(function(button){button.onclick=function(){selectPlatform(button.dataset.platform);el('player-input').value=button.dataset.query;query()}})}
async function remember(query,profile){history=[{platform:profile.platform,query:query}].concat(history.filter(function(item){return item.platform!==profile.platform||item.query.toLowerCase()!==query.toLowerCase()})).slice(0,8);renderHistory();try{await Tapp.storage.set(HISTORY_KEY,history)}catch(e){}}
function selectPlatform(next){if(!providers[next])return;platform=next;sequence++;stopViewer();document.querySelectorAll('[data-player-platform]').forEach(function(button){button.classList.toggle('active',button.dataset.playerPlatform===next)});var input=el('player-input');input.value='';input.placeholder=next==='java'?'输入 Java 玩家名称或 UUID':next==='bedrock'?'输入 Xbox Gamertag、XUID 或 Floodgate UUID':'输入网易玩家 UID';el('player-platform-hint').textContent=next==='java'?'可查询 Java 用户名或 UUID。资料来自 Mojang 公开接口。':next==='bedrock'?'支持 Gamertag、十进制 XUID 和 Floodgate UUID。普通 UUID 不能当作 XUID。':'目前未确认免登录且可靠的网易玩家公开资料接口；仅接受 UID 格式，查询将提示暂不支持。';el('player-result').innerHTML='<div class="empty-state"><h2>输入玩家信息开始查询</h2></div>';try{Tapp.storage.set(PLATFORM_KEY,next)}catch(e){}}
async function query(){var input=el('player-input').value.trim(),seq=++sequence;if(!input){showState('invalid');return}if(platform==='netease'){showState(/^\d{1,20}$/.test(input)?'unsupported':'invalid');return}stopViewer();el('player-result').innerHTML='<div class="loading"><span class="spinner"></span>正在查询公开玩家资料…</div>';var key=platform+':'+input.toLowerCase();try{var hit=cache.get(key),profile=hit&&hit.expires>Date.now()?hit.profile:await providers[platform](input);if(seq!==sequence)return;if(!hit||hit.expires<=Date.now())cache.set(key,{profile:profile,expires:Date.now()+CACHE_MS});if(cache.size>40){cache.forEach(function(value,k){if(value.expires<=Date.now())cache.delete(k)});if(cache.size>40)cache.delete(cache.keys().next().value)}renderProfile(profile);await remember(input,profile)}catch(e){if(seq===sequence)showState(classify(e),input)}}
function showState(code,input){stopViewer();var box=el('player-result');box.innerHTML='<div class="empty-state" role="status"><h2>'+escapeHtml(code==='unsupported'?'暂不支持查询':code==='invalid'||code==='invalid-gamertag'?'请检查输入':code==='uuid-not-xuid'?'UUID 与 XUID 不同':'查询未完成')+'</h2><p>'+escapeHtml(message(code))+'</p>'+(code==='uuid-not-xuid'?'<button type="button" id="player-try-java">用 Java 查询此 UUID</button>':'')+'</div>';if(code==='uuid-not-xuid')el('player-try-java').onclick=function(){selectPlatform('java');el('player-input').value=input;query()}}
function copyText(value){return globalThis.MinecraftHub.copyText(value)}
async function openTexture(url){try{await Tapp.ui.openUrl({id:'minecraft-texture',path:url.slice('https://textures.minecraft.net/texture/'.length)})}catch(e){await copyText(url)}}
function externalImagesAllowed(url){var host='https://textures.minecraft.net';try{if(url)host=new URL(url).origin}catch(e){return false}var meta=document.querySelector('meta[http-equiv="Content-Security-Policy"]');if(meta){var match=/(?:^|;)\s*img-src\s+([^;]+)/i.exec(meta.content||'');if(match)return /(?:^|\s)https:(?:\s|$)/.test(match[1])||match[1].split(/\s+/).includes(host)}
  try{var info=Tapp.lifecycle.getInfo();if(info&&Array.isArray(info.permissions))return info.permissions.includes('media:remote')}catch(e){}return false}
function renderProfile(profile){
  var java=profile.platform==='java',box=el('player-result'),skin=profile.skin,cape=profile.cape;
  var skinAllowed=!!skin&&externalImagesAllowed(skin),capeAllowed=!!cape&&externalImagesAllowed(cape);
  var viewer=java?'<div class="player-viewer"><canvas id="player-canvas" aria-label="玩家三维模型"></canvas><div id="player-viewer-fallback" class="viewer-fallback">正在加载玩家模型…</div><div class="viewer-controls"><button type="button" id="player-auto-rotate" aria-pressed="true">自动旋转</button><button type="button" id="player-idle" aria-pressed="true">Idle</button><button type="button" id="player-reset">重置视角</button></div><p class="hint">拖动旋转 · 滚轮或双指缩放</p></div>':'';
  var fields=java?'<div class="profile-field"><span>模型</span><strong>'+escapeHtml(profile.model==='slim'?'Slim':profile.model==='classic'?'Classic':'未知')+'</strong></div><div class="profile-field"><span>Skin</span><strong>'+(skin?'公开贴图':'无公开贴图')+'</strong></div><div class="profile-field"><span>Cape</span><strong>'+(cape?'公开披风':'无公开披风')+'</strong></div>':profile.details.map(function(d){return'<div class="profile-field"><span>'+escapeHtml(d.label)+'</span><strong>'+escapeHtml(d.value)+'</strong></div>'}).join('');
  var profileCard='<div class="player-profile"><div class="profile-heading"><canvas id="player-head" width="64" height="64" aria-label="玩家头像"'+(skinAllowed?'':' hidden')+'></canvas><div><p class="eyebrow">'+(java?'JAVA EDITION':'BEDROCK EDITION')+'</p><h2>'+escapeHtml(profile.username)+'</h2></div></div><div class="profile-field"><span>'+escapeHtml(profile.idType)+'</span><strong>'+escapeHtml(profile.playerId)+'</strong><button type="button" id="player-copy">复制</button></div>'+fields+'</div>';
  var skinAction=java?'<button type="button" data-texture-url="'+escapeHtml(skin)+'">查看原图</button>':'<button type="button" data-copy-texture="'+escapeHtml(skin)+'">复制贴图链接</button>';
  var skinCard='<article><h3>Skin</h3>'+(skinAllowed?'<img src="'+escapeHtml(skin)+'" alt="玩家 Skin 原图" loading="lazy">':skin?'<p class="muted">当前页面安全策略阻止外部贴图</p>':'<p class="muted">没有公开 Skin</p>')+(skin?skinAction:'')+'</article>';
  var capeCard='<article><h3>Cape</h3>'+(capeAllowed?'<img src="'+escapeHtml(cape)+'" alt="玩家 Cape 原图" loading="lazy"><button type="button" data-texture-url="'+escapeHtml(cape)+'">查看原图</button>':cape?'<p class="muted">当前页面安全策略阻止外部贴图</p><button type="button" data-texture-url="'+escapeHtml(cape)+'">在浏览器查看原图</button>':'<p class="muted">该玩家没有公开披风</p>')+'</article>';
  var headCard='<article><h3>Head</h3>'+(skinAllowed?'<canvas id="player-head-large" width="96" height="96" aria-label="从 Skin 生成的头部头像"></canvas><p class="hint">从 Skin 在本地裁剪</p>':skin?'<p class="muted">当前页面无法裁剪外部贴图</p>':'<p class="muted">没有可用的 Skin</p>')+'</article>';
  var assets=java||skin?'<div class="player-assets'+(java?'':' bedrock-assets')+'">'+skinCard+(java?capeCard:'')+headCard+'</div>':'';
  box.innerHTML='<div class="player-layout">'+viewer+profileCard+'</div>'+assets;
  el('player-copy').onclick=function(){copyText(profile.playerId)};
  box.querySelectorAll('[data-texture-url]').forEach(function(button){button.onclick=function(){openTexture(button.dataset.textureUrl)}});
  box.querySelectorAll('[data-copy-texture]').forEach(function(button){button.onclick=function(){copyText(button.dataset.copyTexture)}});
  if(skinAllowed)loadSkin(profile,sequence);
  else if(java)el('player-viewer-fallback').textContent=skin?'当前 TApp 页面安全策略阻止外部贴图，无法渲染 3D 模型':'该玩家没有可用的公开 Skin，无法显示模型';
}function headFromSkin(img,canvas){if(!canvas)return;var ctx=canvas.getContext('2d');if(!ctx)return;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,8,8,8,8,0,0,canvas.width,canvas.height);if(img.height>=64)ctx.drawImage(img,40,8,8,8,0,0,canvas.width,canvas.height)}
function loadSkin(profile,seq){var img=new Image();img.crossOrigin='anonymous';img.onload=function(){if(seq!==sequence)return;try{headFromSkin(img,el('player-head'));headFromSkin(img,el('player-head-large'))}catch(e){var hint=el('player-head-large');if(hint)hint.replaceWith(document.createTextNode('贴图源未允许跨域裁剪'))}if(profile.platform==='java'&&!el('player-tab').hidden)startViewer(img,profile)};img.onerror=function(){if(seq!==sequence)return;var fallback=el('player-viewer-fallback');if(fallback)fallback.textContent='贴图跨域加载失败，无法在此环境渲染 3D 模型'};img.src=profile.skin}
function faceTexture(THREE,img,rect){var canvas=document.createElement('canvas');canvas.width=rect[2];canvas.height=rect[3];var ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(img,rect[0],rect[1],rect[2],rect[3],0,0,rect[2],rect[3]);var tex=new THREE.CanvasTexture(canvas);tex.magFilter=THREE.NearestFilter;tex.minFilter=THREE.NearestFilter;tex.colorSpace=THREE.SRGBColorSpace;return tex}
function cuboid(THREE,img,w,h,d,faces){var materials=faces.map(function(rect){return new THREE.MeshBasicMaterial({map:faceTexture(THREE,img,rect),transparent:true,side:THREE.FrontSide,depthWrite:true})});return new THREE.Mesh(new THREE.BoxGeometry(w/16,h/16,d/16),materials)}
// Face order: right, left, top, bottom, front, back. Atlas coordinates use 64px skin layout.
function atlas(x,y,w,h,d){return[[x,y+d,d,h],[x+d+w,y+d,d,h],[x+d,y,w,d],[x+d+w,y,w,d],[x+d,y+d,w,h],[x+d+w+d,y+d,w,h]]}
function startViewer(img,profile){stopViewer();var THREE=globalThis.THREE,canvas=el('player-canvas'),fallback=el('player-viewer-fallback');if(!THREE||!canvas){if(fallback)fallback.textContent='当前 TApp 环境未提供 Three.js，3D 模型不可用';return}try{var renderer=new THREE.WebGLRenderer({canvas:canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;var scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,30),root=new THREE.Group(),armWidth=profile.model==='slim'?3:4;scene.add(root);camera.position.set(0,1,4.2);camera.lookAt(0,1,0);
    function add(group,mesh,x,y,z){mesh.position.set(x,y,z);group.add(mesh);return mesh}
    add(root,cuboid(THREE,img,8,8,8,atlas(0,0,8,8,8)),0,1.75,0);if(img.height>=64)add(root,cuboid(THREE,img,9,9,9,atlas(32,0,8,8,8)),0,1.75,0);
    add(root,cuboid(THREE,img,8,12,4,atlas(16,16,8,12,4)),0,1.125,0);if(img.height>=64)add(root,cuboid(THREE,img,8.5,12.5,4.5,atlas(16,32,8,12,4)),0,1.125,0);
    var rightArm=new THREE.Group(),leftArm=new THREE.Group();rightArm.position.set(-(4+armWidth/2)/16,1.5,0);leftArm.position.set((4+armWidth/2)/16,1.5,0);root.add(rightArm,leftArm);add(rightArm,cuboid(THREE,img,armWidth,12,4,atlas(40,16,armWidth,12,4)),0,-.375,0);add(leftArm,cuboid(THREE,img,armWidth,12,4,atlas(img.height>=64?32:40,img.height>=64?48:16,armWidth,12,4)),0,-.375,0);
    var rightLeg=new THREE.Group(),leftLeg=new THREE.Group();rightLeg.position.set(-.125,.75,0);leftLeg.position.set(.125,.75,0);root.add(rightLeg,leftLeg);add(rightLeg,cuboid(THREE,img,4,12,4,atlas(0,16,4,12,4)),0,-.375,0);add(leftLeg,cuboid(THREE,img,4,12,4,atlas(img.height>=64?16:0,img.height>=64?48:16,4,12,4)),0,-.375,0);
    if(img.height>=64){add(rightArm,cuboid(THREE,img,armWidth+.5,12.5,4.5,atlas(40,32,armWidth,12,4)),0,-.375,0);add(leftArm,cuboid(THREE,img,armWidth+.5,12.5,4.5,atlas(48,48,armWidth,12,4)),0,-.375,0);add(rightLeg,cuboid(THREE,img,4.5,12.5,4.5,atlas(0,32,4,12,4)),0,-.375,0);add(leftLeg,cuboid(THREE,img,4.5,12.5,4.5,atlas(0,48,4,12,4)),0,-.375,0)}
    var state={renderer:renderer,scene:scene,camera:camera,root:root,arms:[rightArm,leftArm],legs:[rightLeg,leftLeg],raf:0,auto:true,idle:true,drag:false,yaw:.4,pitch:0,distance:4.2,disposed:false,resize:null,visibility:null};viewer=state;
    function resize(){var width=Math.max(1,canvas.clientWidth),height=Math.max(1,canvas.clientHeight);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix()}state.resize=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;if(state.resize)state.resize.observe(canvas);resize();
    function frame(time){if(state.disposed||document.hidden||el('player-tab').hidden){state.raf=0;return}if(state.auto&&!state.drag)state.yaw+=.003;if(state.idle){var wave=Math.sin(time/550)*.075;rightArm.rotation.x=wave;leftArm.rotation.x=-wave;rightLeg.rotation.x=-wave*.5;leftLeg.rotation.x=wave*.5}else{rightArm.rotation.x=leftArm.rotation.x=rightLeg.rotation.x=leftLeg.rotation.x=0}root.rotation.y=state.yaw;root.rotation.x=state.pitch;camera.position.z=state.distance;renderer.render(scene,camera);state.raf=requestAnimationFrame(frame)}state.raf=requestAnimationFrame(frame);state.visibility=function(){if(!document.hidden&&!state.disposed&&!state.raf)state.raf=requestAnimationFrame(frame)};document.addEventListener('visibilitychange',state.visibility);
    var pointers=new Map(),pinch=0;canvas.onpointerdown=function(e){pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});state.drag=true;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=function(e){var old=pointers.get(e.pointerId);if(!old)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){state.yaw+=(e.clientX-old.x)*.012;state.pitch=Math.max(-.6,Math.min(.6,state.pitch+(e.clientY-old.y)*.008))}else{var points=Array.from(pointers.values()),distance=Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y);if(pinch)state.distance=Math.max(2.7,Math.min(7,state.distance+(pinch-distance)*.012));pinch=distance}};canvas.onpointerup=canvas.onpointercancel=function(e){pointers.delete(e.pointerId);state.drag=pointers.size>0;pinch=0};canvas.onwheel=function(e){e.preventDefault();state.distance=Math.max(2.7,Math.min(7,state.distance+e.deltaY*.004))};
    el('player-auto-rotate').onclick=function(){state.auto=!state.auto;this.setAttribute('aria-pressed',String(state.auto))};el('player-idle').onclick=function(){state.idle=!state.idle;this.setAttribute('aria-pressed',String(state.idle))};el('player-reset').onclick=function(){state.yaw=.4;state.pitch=0;state.distance=4.2};if(fallback)fallback.hidden=true;
    if(profile.cape){var capeImage=new Image();capeImage.crossOrigin='anonymous';capeImage.onload=function(){if(state.disposed)return;var tex=new THREE.Texture(capeImage);tex.needsUpdate=true;tex.magFilter=THREE.NearestFilter;tex.colorSpace=THREE.SRGBColorSpace;var cape=new THREE.Mesh(new THREE.PlaneGeometry(.625,1),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide}));cape.position.set(0,1.05,-.18);root.add(cape)};capeImage.src=profile.cape}
  }catch(e){if(fallback)fallback.textContent='此设备的 WebGL 不可用，仍可查看玩家资料和贴图'}}
function stopViewer(){if(!viewer)return;viewer.disposed=true;cancelAnimationFrame(viewer.raf);if(viewer.resize)viewer.resize.disconnect();if(viewer.visibility)document.removeEventListener('visibilitychange',viewer.visibility);viewer.scene.traverse(function(node){if(node.geometry)node.geometry.dispose();var materials=node.material?Array.isArray(node.material)?node.material:[node.material]:[];materials.forEach(function(material){if(material.map)material.map.dispose();material.dispose()})});viewer.renderer.dispose();viewer=null}
async function init(){try{var saved=await Tapp.storage.get(HISTORY_KEY);history=Array.isArray(saved)?saved.filter(function(x){return x&&providers[x.platform]&&typeof x.query==='string'&&x.platform!=='netease'}).slice(0,8):[]}catch(e){history=[]}renderHistory();var savedPlatform='java';try{savedPlatform=await Tapp.storage.get(PLATFORM_KEY)||'java'}catch(e){}selectPlatform(providers[savedPlatform]?savedPlatform:'java');document.querySelectorAll('[data-player-platform]').forEach(function(button){button.onclick=function(){selectPlatform(button.dataset.playerPlatform)}});el('player-query').onclick=query;el('player-input').onkeydown=function(e){if(e.key==='Enter')query()};el('player-clear-history').onclick=async function(){history=[];renderHistory();try{await Tapp.storage.set(HISTORY_KEY,[])}catch(e){}};observer=new MutationObserver(function(){if(el('player-tab').hidden)stopViewer()});observer.observe(el('player-tab'),{attributes:true,attributeFilter:['hidden']})}
function destroy(){sequence++;stopViewer();if(observer)observer.disconnect()}
module.exports={init:init,destroy:destroy,javaProvider:javaProvider,bedrockProvider:bedrockProvider,neteaseProvider:neteaseProvider,uuid:uuid,floodgateXuid:floodgateXuid,textureUrl:textureUrl,externalImagesAllowed:externalImagesAllowed};
